CREATE TABLE REQUEST (
    ID          CHAR(36)      NOT NULL, -- UUID
    CLIENT_ID   VARCHAR(64)   NOT NULL,
    COMMAND     VARCHAR(64)   NOT NULL,
    ARGS_JSON   VARCHAR(4096) NOT NULL,
    STATUS      VARCHAR(16)   NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_REQUEST_STATUS ON ZEUS1.REQUEST (STATUS);

-- UTF-8 für relevante VARCHAR-Spalten setzen
ALTER TABLE REQUEST ALTER COLUMN CLIENT_ID SET CCSID 1208;
ALTER TABLE REQUEST ALTER COLUMN COMMAND SET CCSID 1208;
ALTER TABLE REQUEST ALTER COLUMN ARGS_JSON SET CCSID 1208;
ALTER TABLE REQUEST ALTER COLUMN STATUS SET CCSID 1208;
