CREATE TABLE RESPONSE (
    ID            CHAR(36)        NOT NULL,
    REQUEST_ID    CHAR(36)        NOT NULL,
    CLIENT_ID     VARCHAR(64)     NOT NULL,
    RESPONSE_JSON VARCHAR(4096)   NOT NULL,
    CREATED_AT    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

ALTER TABLE RESPONSE
ADD CONSTRAINT FK_RESPONSE_REQUEST
FOREIGN KEY (REQUEST_ID)
REFERENCES ZEUS1.REQUEST(ID);

-- UTF-8 für relevante VARCHAR-Spalten setzen
ALTER TABLE REQUEST ALTER COLUMN CLIENT_ID SET CCSID 1208;
ALTER TABLE REQUEST ALTER COLUMN COMMAND SET CCSID 1208;
ALTER TABLE REQUEST ALTER COLUMN ARGS_JSON SET CCSID 1208;
ALTER TABLE REQUEST ALTER COLUMN STATUS SET CCSID 1208;

ALTER TABLE RESPONSE ALTER COLUMN CLIENT_ID SET CCSID 1208;
ALTER TABLE RESPONSE ALTER COLUMN RESPONSE_JSON SET CCSID 1208;

