server:
  port: 9090

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:your#pwd#key}
    algorithm: PBEWithMD5AndDES

spring:
  datasource:
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
    url: jdbc:as400://${AS400_SYSTEM:system};libraries=YOURLIB;translate binary=true
    username: ENC(yourEncryptedUser)
    password: ENC(yourEncryptedPass)
  jpa:
    hibernate:
      ddl-auto: none


  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    check-template-location: true

workflow:
  hot-folder: ${HOT_FOLDER:${user.dir}/hotfolder}
  processed-folder: ${PROCESSED_FOLDER:${user.dir}/processed}
  executeSql:
    defaultQuery: "SELECT 'Fallback' AS Wert FROM SYSIBM.SYSDUMMY1"
  applyTemplate:
    subjectTemplate: classpath:/templates/emailSubject.ftl
    bodyTemplate: classpath:/templates/emailBody.ftl
  transform:
    type: csv

export:
  file-path: ${EXPORT_DIR:./export}
  formats: html, json, jsonl, csv, md

as400:
  system: ${AS400_SYSTEM:YOUR_SYSTEM}
  username: ENC(yourEncryptedUser)
  password: ENC(yourEncryptedPass)

dataqueue:
  library: ${QUEUE_LIBRARY:YOURLIB}
  rpg2java: RP2JQ
  java2rpg: J2RPQ
  key-length: 32
  max-entry-length: 1024
  description: "Java-RPG Integration Queue"

mail:
  host: ${MAIL_HOST:smtp.example.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:user}
  password: ${MAIL_PASSWORD:pass}
  from: noreply@example.com
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

encryption:
  key: ${ENCRYPTION_KEY:yourSuperSecretSuperKey##}

fallback:
  recipients: "my.mail@localhost.local"